# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB5O1PxVHXiqECAaPw5Q3YaNx_4BW839
"""

#!/usr/bin/env python3

import argparse
import pandas as pd


MISSING_TOKENS = ["", "NA", "N/A", "null", "None", "nan", "missing", "not available"]


def try_convert_numeric(series):
    cleaned = (
        series.astype(str)
        .str.strip()
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
        .str.replace("%", "", regex=False)
        .str.replace(r"^\((.*)\)$", r"-\1", regex=True)
    )
    return pd.to_numeric(cleaned, errors="coerce")


def print_basic_structure(df):
    print("=" * 80)
    print("BASIC DATASET STRUCTURE")
    print("=" * 80)
    print(f"Shape: {df.shape}")
    print("\nColumn names:")
    for col in df.columns:
        print(f"- {col}")

    print("\nDtypes:")
    print(df.dtypes)

    print("\nInfo:")
    df.info()


def print_missing_summary(df):
    print("\n" + "=" * 80)
    print("MISSING VALUES SUMMARY")
    print("=" * 80)

    missing_counts = df.isna().sum()
    missing_pct = (missing_counts / len(df) * 100).round(2) if len(df) > 0 else 0

    summary = pd.DataFrame({
        "missing_count": missing_counts,
        "missing_percent": missing_pct
    }).sort_values(by="missing_count", ascending=False)

    print(summary)


def print_numeric_summary(df):
    print("\n" + "=" * 80)
    print("NUMERIC SUMMARY")
    print("=" * 80)

    numeric_df = pd.DataFrame(index=df.index)

    for col in df.columns:
        converted = try_convert_numeric(df[col])
        non_null_ratio = converted.notna().mean()

        if non_null_ratio >= 0.8 and converted.notna().sum() > 0:
            numeric_df[col] = converted

    if numeric_df.shape[1] == 0:
        print("No numeric-like columns detected.")
        return

    print(numeric_df.describe().T)

    print("\nAdditional medians:")
    print(numeric_df.median(numeric_only=True))


def print_categorical_summary(df):
    print("\n" + "=" * 80)
    print("CATEGORICAL SUMMARY")
    print("=" * 80)

    for col in df.columns:
        numeric_candidate = try_convert_numeric(df[col])
        non_null_ratio = numeric_candidate.notna().mean()

        if non_null_ratio >= 0.8 and numeric_candidate.notna().sum() > 0:
            continue

        print(f"\nColumn: {col}")
        print("-" * 80)

        series = df[col].dropna().astype(str).str.strip()
        series = series[~series.str.lower().isin([x.lower() for x in MISSING_TOKENS])]

        print(f"Non-null count: {series.shape[0]}")
        print(f"Unique values : {series.nunique()}")

        if series.shape[0] > 0:
            vc = series.value_counts()
            print(f"Mode          : {vc.index[0]}")
            print(f"Mode frequency: {vc.iloc[0]}")
            print("Top 5 values:")
            print(vc.head(5))
        else:
            print("No non-null values available.")


def compare_numeric_columns(df):
    print("\n" + "=" * 80)
    print("COLUMN-WISE NUMERIC VERIFICATION")
    print("=" * 80)

    for col in df.columns:
        converted = try_convert_numeric(df[col])
        non_null = converted.dropna()

        if non_null.shape[0] == 0:
            continue

        ratio = converted.notna().mean()
        if ratio < 0.8:
            continue

        print(f"\nColumn: {col}")
        print(f"Count  : {non_null.count()}")
        print(f"Mean   : {non_null.mean()}")
        print(f"Min    : {non_null.min()}")
        print(f"Max    : {non_null.max()}")
        print(f"Std    : {non_null.std()}")
        print(f"Median : {non_null.median()}")


def main():
    parser = argparse.ArgumentParser(
        description="Compute descriptive statistics using pandas."
    )
    parser.add_argument(
        "csv_file",
        nargs="?",
        default="data/2024_facebook_political_ads.csv",
        help="Path to the CSV dataset file"
    )

    args, unknown = parser.parse_known_args()

    df = pd.read_csv(
        args.csv_file,
        encoding="utf-8-sig",
        na_values=MISSING_TOKENS,
        keep_default_na=True
    )

    print_basic_structure(df)
    print_missing_summary(df)

    print("\n" + "=" * 80)
    print("DESCRIBE() FOR ALL COLUMNS")
    print("=" * 80)
    print(df.describe(include="all").T)

    print_numeric_summary(df)
    print_categorical_summary(df)
    compare_numeric_columns(df)


if __name__ == "__main__":
    main()



