# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PB5O1PxVHXiqECAaPw5Q3YaNx_4BW839
"""

#!/usr/bin/env python3

import csv
import math
import argparse
from collections import Counter
from datetime import datetime


MISSING_TOKENS = {"", "na", "n/a", "null", "none", "nan", "not available", "missing"}


def is_missing(value):
    if value is None:
        return True
    return str(value).strip().lower() in MISSING_TOKENS


def clean_string(value):
    return str(value).strip()


def try_parse_number(value):
    if value is None:
        return None

    s = str(value).strip()
    if is_missing(s):
        return None

    s = s.replace(",", "")
    s = s.replace("$", "")
    s = s.replace("%", "")

    if s.startswith("(") and s.endswith(")"):
        s = "-" + s[1:-1]

    try:
        return float(s)
    except ValueError:
        return None


def try_parse_date(value):
    if value is None:
        return None

    s = str(value).strip()
    if is_missing(s):
        return None

    date_formats = [
        "%Y-%m-%d",
        "%m/%d/%Y",
        "%m/%d/%y",
        "%Y/%m/%d",
        "%b %d, %Y",
        "%B %d, %Y",
        "%Y-%m-%d %H:%M:%S",
        "%m/%d/%Y %H:%M:%S",
    ]

    for fmt in date_formats:
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue

    return None


def infer_column_type(values):
    non_missing = [v for v in values if not is_missing(v)]
    if not non_missing:
        return "empty"

    numeric_count = sum(1 for v in non_missing if try_parse_number(v) is not None)
    date_count = sum(1 for v in non_missing if try_parse_date(v) is not None)

    total = len(non_missing)

    if numeric_count == total:
        return "numeric"
    if date_count == total:
        return "date"
    if numeric_count / total >= 0.8:
        return "mostly_numeric"
    if date_count / total >= 0.8:
        return "mostly_date"
    return "categorical"


def median(values):
    n = len(values)
    if n == 0:
        return None
    sorted_vals = sorted(values)
    mid = n // 2
    if n % 2 == 1:
        return sorted_vals[mid]
    return (sorted_vals[mid - 1] + sorted_vals[mid]) / 2


def sample_std_dev(values):
    n = len(values)
    if n < 2:
        return 0.0
    avg = sum(values) / n
    variance = sum((x - avg) ** 2 for x in values) / (n - 1)
    return math.sqrt(variance)


def compute_numeric_stats(values):
    nums = [try_parse_number(v) for v in values]
    nums = [x for x in nums if x is not None]

    if not nums:
        return {
            "count": 0,
            "mean": None,
            "min": None,
            "max": None,
            "std_dev": None,
            "median": None,
        }

    return {
        "count": len(nums),
        "mean": sum(nums) / len(nums),
        "min": min(nums),
        "max": max(nums),
        "std_dev": sample_std_dev(nums),
        "median": median(nums),
    }


def compute_categorical_stats(values):
    cleaned = [clean_string(v) for v in values if not is_missing(v)]

    if not cleaned:
        return {
            "count": 0,
            "unique": 0,
            "mode": None,
            "mode_frequency": 0,
            "top_5": [],
        }

    freq = Counter(cleaned)
    mode_value, mode_freq = freq.most_common(1)[0]

    return {
        "count": len(cleaned),
        "unique": len(freq),
        "mode": mode_value,
        "mode_frequency": mode_freq,
        "top_5": freq.most_common(5),
    }


def load_csv(path):
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        fieldnames = reader.fieldnames if reader.fieldnames else []
    return fieldnames, rows


def missing_value_counts(rows, columns):
    result = {}
    for col in columns:
        result[col] = sum(1 for row in rows if is_missing(row.get(col)))
    return result


def collect_column_values(rows, columns):
    column_data = {col: [] for col in columns}
    for row in rows:
        for col in columns:
            column_data[col].append(row.get(col))
    return column_data


def print_dataset_summary(rows, columns, missing_counts, inferred_types):
    print("=" * 80)
    print("DATASET OVERALL SUMMARY")
    print("=" * 80)
    print(f"Total rows   : {len(rows)}")
    print(f"Total columns: {len(columns)}")
    print()

    print("Missing Values Per Column")
    print("-" * 80)
    for col in columns:
        print(f"{col}: {missing_counts[col]}")
    print()

    print("Inferred Data Types")
    print("-" * 80)
    for col in columns:
        print(f"{col}: {inferred_types[col]}")
    print()


def print_column_analysis(columns, column_data, inferred_types):
    print("=" * 80)
    print("COLUMN-BY-COLUMN ANALYSIS")
    print("=" * 80)

    for col in columns:
        print(f"\nColumn: {col}")
        print("-" * 80)
        inferred = inferred_types[col]
        print(f"Inferred type: {inferred}")

        if inferred in {"numeric", "mostly_numeric"}:
            stats = compute_numeric_stats(column_data[col])
            print(f"Non-null count     : {stats['count']}")
            print(f"Mean               : {stats['mean']}")
            print(f"Minimum            : {stats['min']}")
            print(f"Maximum            : {stats['max']}")
            print(f"Standard deviation : {stats['std_dev']}")
            print(f"Median             : {stats['median']}")
        else:
            stats = compute_categorical_stats(column_data[col])
            print(f"Non-null count     : {stats['count']}")
            print(f"Unique values      : {stats['unique']}")
            print(f"Mode               : {stats['mode']}")
            print(f"Mode frequency     : {stats['mode_frequency']}")
            print("Top 5 values by frequency:")
            for value, freq in stats["top_5"]:
                print(f"  - {value}: {freq}")


def main():
    parser = argparse.ArgumentParser(
        description="Compute descriptive statistics using only the Python standard library."
    )
    parser.add_argument(
        "csv_file",
        nargs="?",
        default="data/2024_facebook_political_ads.csv",
        help="Path to the CSV dataset file"
    )

    args, unknown = parser.parse_known_args()

    columns, rows = load_csv(args.csv_file)

    if not columns:
        print("Error: CSV file appears to have no header row.")
        return

    column_data = collect_column_values(rows, columns)
    missing_counts = missing_value_counts(rows, columns)
    inferred_types = {col: infer_column_type(column_data[col]) for col in columns}

    print_dataset_summary(rows, columns, missing_counts, inferred_types)
    print_column_analysis(columns, column_data, inferred_types)


if __name__ == "__main__":
    main()



